## Numpy Library Exercises

In [2]:
import numpy as np

**1.** Given a random array, change the sign of elements with values between 3 and 8

In [4]:
# your code
rng = np.random.default_rng()

random_array = rng.integers(1, 20, (15))

random_array[(random_array >= 3) & (random_array <= 8)] *= -1

random_array

array([16, -8, 15, 10, 12, 11, 13, 14, 16, 19, -5, -3, 14, 19, 12])

**2.** Replace the maximum element of a random array with 0

In [16]:
# your code
random_array = rng.integers(1, 20, (15))

print(random_array)
random_array[random_array == random_array.max()] = 0
print(random_array)

[11  9 10  7  2 10 16  9  4 17  1  8 19 19 16]
[11  9 10  7  2 10 16  9  4 17  1  8  0  0 16]


**3.** Construct the Cartesian product of arrays (all combinations with each element). The input is a two-dimensional array.

In [ ]:
# your code
arr1 = rng.integers(0, 5, (2, 2))
arr2 = rng.integers(5, 10, (2, 2))
A, B = np.meshgrid(arr1, arr2)

result = np.column_stack([A.ravel(), B.ravel()])

result

array([[1, 5],
       [3, 5],
       [2, 5],
       [0, 5],
       [1, 9],
       [3, 9],
       [2, 9],
       [0, 9],
       [1, 9],
       [3, 9],
       [2, 9],
       [0, 9],
       [1, 8],
       [3, 8],
       [2, 8],
       [0, 8]])

**4.** Given two arrays A (8x3) and B (2x2). Find rows in A that contain elements from every row in B, regardless of the order of elements in B

In [ ]:
# your code
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 3, 4],
    [1, 4, 5],
    [2, 5, 6],
    [3, 4, 6],
    [1, 2, 4],
    [2, 3, 5]
])

B = np.array([
    [2, 3],
    [4, 5]
])

mask = np.array([
    any(np.isin(b_row, a_row).all() for b_row in B)
    for a_row in A
])

result = A[mask]
print(result)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [1 4 5]
 [2 3 5]]


**5.** Given a 10x3 matrix, find rows consisting of unequal values (e.g., row [2,2,3] remains, row [3,3,3] is removed)

In [19]:
# your code
arr = rng.integers(1, 2, (10, 3))
arr[np.ptp(arr, axis=1) != 0]

array([], shape=(0, 3), dtype=int64)

**6.** Given a two-dimensional array. Remove duplicate rows

In [48]:
# your code
arr = rng.integers(1, 5, (5, 2))
unique = np.unique(arr, axis=0)
unique

array([[1, 1],
       [1, 2],
       [3, 4],
       [4, 4]])

______
______

For each of the following tasks (1-5), you need to provide 2 implementations – one without using numpy (assume that where the input or output should be a numpy array, it will simply be a list), and the second fully vectorized using numpy (without using Python loops/map/list comprehension).


**Note 1.** You can assume that all specified objects are non-empty (for example, in **Task 1** there are non-zero elements on the diagonal of the matrix).

**Note 2.** For most tasks, the solution takes no more than 1-2 lines.

___

* **Task 1**: Calculate the product of non-zero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) the answer is 3.

In [2]:
# your code
#numpy_version
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diagonal = np.diag(X)

product = np.prod(diagonal[diagonal != 0])
product

np.int64(3)

* **Task 2**: Given two vectors x and y. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) the answer is True.

In [5]:
# your code
#numpy_version
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(np.array_equal(np.sort(x), np.sort(y)))

#python_version
from collections import Counter

print(Counter(x) == Counter(y))

True
True


* **Task 3**: Find the maximum element in vector x among the elements preceded by a zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) the answer is 5.

In [4]:
# your code
#numpy_version
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

print(np.max(x[1:][x[:-1] == 0]))

#python_version
candidates = [x[i] for i in range(1, len(x)) if x[i-1] == 0]
print(max(candidates))

5
5
